"""
Temporary artifact registry for files generated by the server.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from threading import Lock
from uuid import uuid4


@dataclass
class ArtifactRecord:
    """Metadata describing a temporary server-side artifact."""

    artifact_id: str
    path: Path
    filename: str
    expires_at: datetime


class ArtifactStore:
    """In-memory registry for temporary files exposed over HTTP."""

    def __init__(self, ttl_seconds: int = 3600):
        self._ttl = timedelta(seconds=ttl_seconds)
        self._items: dict[str, ArtifactRecord] = {}
        self._lock = Lock()

    def register_file(self, path: Path | str, filename: str) -> ArtifactRecord:
        """Register a generated file and return the created artifact record."""
        resolved_path = Path(path).resolve()
        record = ArtifactRecord(
            artifact_id=uuid4().hex,
            path=resolved_path,
            filename=filename,
            expires_at=datetime.now(timezone.utc) + self._ttl,
        )

        with self._lock:
            self._cleanup_locked()
            self._items[record.artifact_id] = record

        return record

    def get(self, artifact_id: str) -> ArtifactRecord | None:
        """Return a non-expired artifact record if it still exists on disk."""
        with self._lock:
            self._cleanup_locked()
            return self._items.get(artifact_id)

    def _cleanup_locked(self) -> None:
        """Remove expired or missing artifacts. Caller must hold the lock."""
        now = datetime.now(timezone.utc)
        expired_ids = [
            artifact_id
            for artifact_id, record in self._items.items()
            if record.expires_at <= now or not record.path.exists()
        ]
        for artifact_id in expired_ids:
            record = self._items.pop(artifact_id, None)
            if record is not None:
                record.path.unlink(missing_ok=True)


artifact_store = ArtifactStore()
